<!-- Page d'ajout d'un article -->
<h2><i class="fa fa-pencil"></i> Enregistrez vous </h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="register.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel utilisateur</legend>
        <ul>
            <li>
                <label for="lastName">Nom :</label>
                <input type="text" id="lastName" name="lastName">
            </li>
            <li>
                <label for="firstName">Prénom :</label>
                <input type="text" id="firstName" name="firstName">
            </li>
            <li>
                <label for="pseudo">Pseudo :</label>
                <input type="text" id="pseudo" name="pseudo">
            </li>
            <li>
                <label for="email">Email :</label>
                <input type="text" id="firstName" name="email">
            </li>
            <li>
                <label for="password">Mot de Passe :</label>
                <input type="password" id="password" name="password">
            </li>
            <li>
                <button class="button button-primary" type="submit">Bienvenue</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>