<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Exam</title>
	<link rel="stylesheet" href="index.css">
	  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
<body>
	
	<h1>BONJOUR</h1>
	
	<ul>
  <li>Lorem</li>
  <li class="even">Ipsum</li>
  <li>Dolor</li>
  <li class="even">Sit</li>
  <li>Amet</li>
</ul>









	<script type="text/javascript" charset="utf-8" src="index.js"></script>
</body>
</html>