<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>Document</title>
</head>
<body>
<main>
       <!-- Chargement du template PHTML spécifié par le programme PHP -->
       <!-- Page d'édition d'un article -->
<h2><i class="fa fa-pencil"></i> Editer un article</h2>

<!-- Formulaire de mise à jour d'un article -->
<form class="generic-form" action="change_content.php?id=<?= $_GET['id'] ?>" method="post">

   <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
   <input type="hidden" name="postId" value="">

   <fieldset>
       <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
       <ul>

           <li>

               <label for="title">Titre :</label>
               <input type="text" id="title" name="title" value="<?= htmlspecialchars($change['Title']) ?>">
           </li>
           <li>
               <label class="textarea" for="contents">Article :</label>
               <textarea id="contents" name="contents" rows="15"><?= htmlspecialchars($change['Contents']) ?> </textarea>
           </li>
           <li>
               <button class="button button-primary" type="submit">Mettre à jour</button>
               <a class="button button-cancel" href="index.php">Annuler</a>
           </li>

       </ul>
   </fieldset>
</form>    </main>
</body>
</html>