<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Encore un Blog ?! #nonMaisAllo</title>
</head>
<body>
<main>
	<h2><i class="fas fa-home"></i> Accueil</h2>
	 <?php foreach ( $indexRecup as $indexRecups ): ?>
	<h3><i class="far fa-hand-point-right"></i> <a href="show_post.php?id=<?= $indexRecups['Id'] ?>"><?= htmlspecialchars($indexRecups['Title']) ?></a></h3>
	<article>
	<?= substr($indexRecups['Contents'],0 ,100) ?> [...]
	</article>
	<small>Rédiger par <?= $indexRecups['FirstName'].' '.$indexRecups['LastName'].' le '.$indexRecups['CreationDate'] ?></small>
	<?php endforeach ?>
</main>
	
</body>
</html>