<form class="generic-form" action="/dev/Restaurant/index.php/user/login" method="POST">

<aside class="error-message hidden">
   <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
   <p></p>
</aside>

<fieldset>
   <legend>Informations d'authentification</legend>
   <ul>
       <li>
           <label for="email">E-mail :</label>
           <input id="email" type="text" name="email" data-required="" data-name="E-mail" value="">
       </li>
       <li>
           <label for="password">Mot de passe :</label>
           <input id="password" type="password" name="password" data-required="" data-name="Mot de passe">
       </li>
   </ul>
</fieldset>

<ul>
   <li>
       <input class="button button-primary" type="submit" value="Connexion">
       <a class="button button-cancel small" href="/Restaurant (corrigé)/index.php">Annuler</a>
   </li>
</ul>
</form>