   <img src="images/activiteBanner.jpeg" alt="" width='100%'>

<main class="container">

	<div class="partage">


		<h2>Ici nous pourrons partager</h2>

		<hr>
		
		<?php foreach ($experienceRecup as $experienceRecups ): ?>
				
			<?php if ($experienceRecups['Status'] == 'accept') {?>

					<h3><?= htmlspecialchars($experienceRecups['Title']) ?></h3>

					<img src="recupImages/<?= $experienceRecups['file'] ?>" alt="">
				
					<p><?= htmlspecialchars($experienceRecups['Contents']) ?></p>
			
			
		
					<p class='auteur'>Rédigé par : <?= htmlspecialchars($experienceRecups['pseudo']) ?></p>

					<p class='auteur'>Fait le : <?= htmlspecialchars($experienceRecups['CreationDate']) ?></p>
			
				<?php if (array_key_exists('role', $_SESSION) && ($_SESSION['role'] == 'admin' || $_SESSION['Id'] == $experienceRecups['userId'] )) { ?>

					<a class="edit" href="edit.php?id=<?= intval($experienceRecups['Id']) ?>"><button>Modifier</button></a>
					<a href="delete.php?id=<?= intval($experienceRecups['Id']) ?>"><button>Supprimer</button></a>

				<?php } else { ?>
					
				<?php }?>

	

			
				<div class="clear">
				</div>

				<hr>
			
			<?php }?>

		<?php endforeach ?>
		
	</div>

</main>