<img src="images/rediger.jpg" alt="" width="100%">

<h2>Rédiger un nouvel article</h2>

<form class="generic-form" action="rediger.php" method="post" enctype="multipart/form-data">
    <fieldset>
        <ul class="formulaire">
            <li>
                <label for="title">Titre :</label>
                <input class="borderValid" type="text" id="title" name="title" required>
            </li>
            
            <input class="choixFichier" name="photoProfil" type="file" required/>

            <li>
                <label class='articleTop' for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15" class="borderValid" required></textarea>
            </li>

            <li class="buttonLogin">
                <button class="button button-primary" type="submit">Enregistrer</button>

                <button><a class="button button-cancel" href="">Annuler</a></button>
            </li>
        </ul>
    </fieldset>
</form>