<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Loterie 3Wacademy</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="lottery.css">
</head>
<body>
    <header>
        <h1>Traducteur Tagalog - Français</h1>
    </header>

    <p>coucou</p>
    <p>Je m'appelle <?= $name ?></p>
    <p><?= $result ?></p>
    <p><?= $dico['name'] ?></p>
</body>
</html>