<img src="../images/activiteBanner.jpeg" alt="">

<main class="container">

	<div class="partage">


		<h2>Ici nous pourrons partager</h2>

		<hr>

		<?php foreach ( $experienceRecup as $experienceRecups ): ?>

				<h3><?= htmlspecialchars($experienceRecups['Title']) ?></h3>

				

				<p><?= htmlspecialchars($experienceRecups['Contents']) ?></p>
		
		
	
				<p class='auteur'>Rédiger par : <?= htmlspecialchars($experienceRecups['pseudo']) ?></p>
			
			<?php if (array_key_exists('role', $_SESSION) && ($_SESSION['role'] == 'admin' || $_SESSION['Id'] == $experienceRecups['userId'] )) { ?>

				<a class="edit" href="edit.php?id=<?= intval($experienceRecups['Id']) ?>"><button>Modifier</button></a>
				<a href="delete.php?id=<?= intval($experienceRecups['Id']) ?>"><button>Supprimer</button></a>

			<?php } else { ?>
				
			<?php }?>

			

				<hr>

		<?php endforeach ?>
		

		<div class="clear">
		</div>

	</div>


</main>