<img src="../images/background.jpg" alt="">


<div class="container">
	<?php if ($_SESSION != null) { ?>
		<p>Bonjour <?= $_SESSION['Pseudo']?>, vous êtes connectés.</p>
	<?php } ?>

	<article>
		<h2>Introduction</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus amet temporibus et, totam quae libero. Enim architecto dolore quidem amet eligendi numquam hic obcaecati facilis nemo, magnam dolor quod nobis?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam ipsa et consectetur eaque, itaque distinctio quibusdam laudantium. Doloribus hic quaerat minima cum, sint ipsa tempora dolore expedita, eveniet nihil non.</p>
	</article>

		<hr>

	<article>
		<h2></h2>
	</article>

	<article id="faq">
		<div>
			<h2>F.A.Q</h2>
		</div>
	</article>
</div>

	<div class="hautFooter">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3847.529167589614!2d121.05457435100996!3d15.347801689277782!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397249f93136973%3A0xc7a4437247020cce!2sBrgy+Concepcion!5e0!3m2!1sfr!2sfr!4v1548254123864" width="1900" height="250" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>