<main>
    <img src="../images/contactBanner.jpeg" alt="" width="100%">

<div class="container">
    <h2>Connectez vous !</h2>
    
    <?php if ($error == true ) {?>
        <div>
            <p> <?= $message ?></p>
        </div>
    <?php } ?>

<form class="generic-form" action="login.php" method="POST">
    <fieldset>
        <ul class="formulaireRegister">
            <li>
                <label for="email">Email :</label>
                <input type="text" id="firstName" name="email">
            </li>

            <li>
                <label for="password">Mot de Passe :</label>
                <input type="password" id="password" name="password">
            </li>

            <li class="buttonLogin">
                <button class="button button-primary" type="submit">Connexion</button>
                <button><a class="button button-cancel" href="index.php">Annuler</a></button>
            </li>
        </ul>
    </fieldset>
</form>
</div>

</main>