<img src="../images/rediger.jpg" alt="" width="100%">

<h2>Rédiger un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="rediger.php" method="post">
    <fieldset>
        <ul class="formulaireRegister">
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>

            <li>
                <label class='articleTop' for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15"></textarea>
            </li>

            <li class="buttonLogin">
                <button class="button button-primary" type="submit">Enregistrer</button>

                <button><a class="button button-cancel" href="">Annuler</a></button>
            </li>
        </ul>
    </fieldset>
</form>