<img src="../images/contactBanner.jpeg" alt="" width="100%">

<main class="container">
	<h2> Inscrivez vous !</h2>

<form class="generic-form" action="register.php" method="post">
	<fieldset>
		<ul class="formulaireRegister">
			<li>
				<label for="Mail">Mail :</label>
				<input type="text" id="Mail" name='Mail'>
			</li>

			<li>
				<label for="Password">Password :</label>
				<input type="text" id="Password" name='Password'>
			</li>

			<li>
				<label for="Prénom">Prénom :</label>
				<input type="text" id="Prénom" name='Prénom'>
			</li>
			
			<li>
				<label for="Nom">Nom :</label>
				<input type="text" id="Nom" name='Nom'>
			</li>

			<li>
				<label for="Pseudo">Pseudo :</label>
				<input type="text" id="Pseudo" name="Pseudo">
			</li>

			<li class="buttonLogin">
				 <button class="button button-primary" type="submit">Enregistrer</button>
                <button><a class="button button-cancel" href="index.php">Annuler</a></button>
			</li>
		</ul>
	</fieldset>
</form>
</main>