	
<!DOCTYPE html>
<html>
   <head>
      <title>index</title>
      	<meta charset="utf-8">
      	<link rel="stylesheet" type="text/css" href="style.css">
      </head>
      <body>
      	<div>
            <nav>
                <a href="index.php">Home</a>
                <a href="form.php">lien vers le formulaire</a>
                <a href="get.php?name=Paul&id=32">lien vers le get de Paul</a>
                <a href="get.php?name=Jacques&id=14">lien vers le get de Jacques</a>
                <a href="get.php?name=Pierre&id=39">lien vers le get de Pierre</a>
            </nav>
            <p> Je suis le header</p>

		</div>